name: Build and push docker images

on:
  push:
    branches:
      - master
      - hdl-dev

jobs:
  docker:
    runs-on: ubuntu-18.04
    timeout-minutes: 300

    steps:
      - uses: actions/checkout@v1

      - name: Build image
        env:
          TAG: ${{ github.ref }}
        shell: bash
        run: |
          docker build -t hdwlab/webviz:${TAG##*/} .

      - name: Push to DockerHub
        env:
          TAG: ${{ github.ref }}
          DOCKER_USER: ${{ secrets.DOCKER_USER }}
          DOCKER_PASS: ${{ secrets.DOCKER_PASS }}
        shell: bash
        run: |
          docker login -u ${DOCKER_USER} -p ${DOCKER_PASS} \
          && docker push hdwlab/webviz:${TAG##*/}
